### ISSUE TITLE
make gcs url public & export the job output as a url instead of using the bucket

### ISSUE THREAD

**Issue by thiagopnts** [NYTimes/video-captions-api#67]
1. in the `JobOuput` URL, instead of `gs://video-captions-api-dev/2017/8/1/73394_1_opdoc-drive-in-jesus_wg_480p.vtt` we want to have a direct URL like `https://storage.googleapis.com/video-captions-api-dev/2017/8/1/73394_1_opdoc-drive-in-jesus_wg_480p.vtt`
2. the URL should be public

**Comment by markx** [comment]
fixed by #68
